[tool.poetry]
name = "runcached"
version = "0.1.0"
description = ""
authors = ["Tim Vergenz <vergenzt@gmail.com>"]

[tool.poetry.dependencies]
python="^3.9"
appdirs = "^1.4.4"
diskcache = "^5.4.0"
docopt = "^0.6.2"
pytimeparse = "^1.1.8"
strongtyping = "^2"
ConfigArgParse = "^1.5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-mock = "^3.7.0"
pytest-cov = "^3.0.0"

[tool.poetry.scripts]
runcached = 'runcached.main:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
